INSERT INTO Manufacturers (Title, Country) VALUES ('Rolex', 'Switzerland'),
                                                  ('Omega', 'Switzerland'),
                                                  ('IWC', 'Switzerland'),
                                                  ('Hublot', 'Switzerland'),
                                                  ('TAG Heuer', 'Switzerland'),
                                                  ('Patek Philippe', 'Switzerland'),
                                                  ('Zenith', 'Switzerland'),
                                                  ('Casio', 'Japan'),
                                                  ('Citizen', 'Japan'),
                                                  ('Seiko', 'Japan'),
                                                  ('Cartier', 'France'),
                                                  ('Invicta Watch', 'France'),
                                                  ('Pierre Lannier', 'France'),
                                                  ('Emile Pequignet', 'France'),
                                                  ('Luch', 'Belarus'),
                                                  ('Hvilina', 'Belarus'),
                                                  ('Casio', 'Japan');